#!/bin/sh

echo Commiting as $(git config user.email)

# Lint backend source code
git diff --name-only --cached --diff-filter ACMR | grep -E ".php$" | xargs --no-run-if-empty ./vendor/bin/phpcs

# Lint frontend source code
git diff --name-only --cached --diff-filter ACMR | grep -E ".(js|vue)$" | xargs --no-run-if-empty yarn eslint
